# Generated by Django 5.2 on 2025-05-03 07:48

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_categorias_options_alter_destinos_fecha_salida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reserva de Viaje', 'verbose_name_plural': 'Reservas de Viajes'},
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[accounts.models.positive_price_validator], verbose_name='Cantidad de pasajes'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_destino',
            field=models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.CASCADE, to='accounts.destinos', verbose_name='Destino seleccionado'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='id_metodoPago',
            field=models.ForeignKey(db_column='id_metodoPago', on_delete=django.db.models.deletion.CASCADE, to='accounts.metodopago', verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
